export { default as TableSkeleton } from './TableSkeleton'
export { default as ListSkeleton } from './ListSkeleton'
export { default as CardGridSkeleton } from './CardGridSkeleton'
export { default as StudentListSkeleton } from './StudentListSkeleton'
export { default as SidebarSkeleton } from './SidebarSkeleton'
export { default as ClassCardSkeleton } from '../ClassCardSkeleton'
